name: Build and Test Notimpo GitHub actions

on:
  push:
    branches:
    - master

jobs:
  build_and_test:
    name: Build and test the GitHub Action
    strategy:
      matrix:
        os: [ 'ubuntu-latest' ]
        dotnet: [ '3.1.100' ]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: ${{ matrix.dotnet }}

    - name: Restore NuGet packages
      shell: bash
      run: |
        dotnet restore
    - name: Build console app
      shell: bash
      run: |
        dotnet build
    - name: Run the private action
      uses: shaijut/Notimpo@v2
      with:
        mailgun_api_key: '123456'
        to: 'to@example.com'
        from: 'from@example.com'
        subject: 'Test subject'
        message: 'Test message'
        notify_type: 'email'
        
