name: 'A test'
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Notimpo:
    runs-on: ubuntu-latest
    steps:
      - uses: shaijut/Notimpo
        with:
            first_name: 'John'

